title: "Yonaga"
baseurl: "" # Leave empty for a user or organization site
description: "Yonaga is dedicated to providing intuitive tools for professionals. Discover our popular app, Angulus, used worldwide by clinical experts for precise angle measurements."
theme: jekyll-theme-midnight
google_analytics: G-KPY2DKJWP3
